name: Radar Lambda functions

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy functions
        run: |
          zip -j deployAddTask ./src/radarAddTask/index.js
          zip -j deployDeleteTask ./src/radarDeleteTask/index.js
          zip -j deployGetTasks ./src/radarGetTasks/index.js
          zip -j deployGetTask ./src/radarGetTask/index.js
          zip -j deployUpdateTask ./src/radarUpdateTask/index.js
          zip -j deploySchedulerTask ./src/radarNotificationScheduler/index.js
          aws lambda update-function-code --function-name=radarAddTask --zip-file=fileb://deployAddTask.zip
          aws lambda update-function-code --function-name=radarDeleteTask --zip-file=fileb://deployDeleteTask.zip
          aws lambda update-function-code --function-name=radarGetTasks --zip-file=fileb://deployGetTasks.zip
          aws lambda update-function-code --function-name=radarGetTask --zip-file=fileb://deployGetTask.zip
          aws lambda update-function-code --function-name=radarUpdateTask --zip-file=fileb://deployUpdateTask.zip
          aws lambda update-function-code --function-name=radarNotificationScheduler --zip-file=fileb://deploySchedulerTask.zip
